### PR TITLE
Add WoodpeckerCI

### LINKED ISSUE #54: Add WoodpeckerCI
variables: https://woodpecker-ci.org/docs/usage/environment#built-in-environment-variables
repos: https://github.com/woodpecker-ci
website: https://woodpecker-ci.org/

### PR DESCRIPTION
**Pull request by 6543**
close #54

### CODE REVIEW

**Comment by 6543** [comment]
@siddharthkp :wave:

**Comment by 6543** [comment]
Test run logs:
pull: [CI-Tests-siddharthkp_ci-env-17-build.log](https://github.com/siddharthkp/ci-env/files/9150957/CI-Tests-siddharthkp_ci-env-17-build.log)
 
push: [CI-Tests-siddharthkp_ci-env-16-build.log](https://github.com/siddharthkp/ci-env/files/9150959/CI-Tests-siddharthkp_ci-env-16-build.log)

**Comment by 6543** [comment]
@siddharthkp tested localy with woodpecker ci now :)

**Comment by 6543** [comment]
@siddharthkp gh-actions needs aproval

**Comment by 6543** [comment]
It passed - do I need to do something else ?

**Comment by 6543** [comment]
@siddharthkp  do I need to do something else ?

**Comment by siddharthkp** [comment]
Nope, all good!

Released as 1.18.0

**Pull request merged**
