### PR TITLE
Add buildUrl

### PR DESCRIPTION
**Pull request by Kikobeats**
Based on https://github.com/siddharthkp/ci-env/pull/19 but more clean.

### CODE REVIEW

**Comment by siddharthkp** [comment]
Hi!

This is a backward breaking change! Any package that uses the old variable will fail.

We'd have to keep both variables if you'd like to add a new one

**Comment by Kikobeats** [comment]
added again 🙂

**Comment by siddharthkp** [comment]
Should we just say `jobUrl` = `buildUrl` ?

**Comment by siddharthkp** [comment]
Published in 1.7.0 :shipit:

**Pull request merged**
