### PR TITLE
Add support for Codefresh

### PR DESCRIPTION
**Pull request by LironEr**

### CODE REVIEW

**Comment by siddharthkp** [comment]
Hey! can you also add update tests :)

I have no idea how to test this, it would be cool if you can setup codefresh as well

**Comment by LironEr** [comment]
No problem, I just need you to add a webhook to Codefresh, I sent you an email with instructions.

**Comment by LironEr** [comment]
@siddharthkp any update? :)

**Comment by siddharthkp** [comment]
@kuldeepkeshwar Feel free to ship it :shipit:

**Pull request merged**
