### PR TITLE
support GitHub Actions

### PR DESCRIPTION
**Pull request by njzjz**

### CODE REVIEW

**Comment by siddharthkp** [comment]
This is great! What would be a good way to add tests for these?

**Comment by njzjz** [comment]
I have added GitHub Actions for pull request and push, but I think you should [register for GitHub Actions Beta](https://github.com/features/actions/signup/)?

**Comment by siddharthkp** [comment]
Thanks Jinzhe!

**Comment by siddharthkp** [comment]
Published in `1.9.0`

**Pull request merged**
